### ISSUE TITLE
Error while installing this jekyll-theme

### ISSUE THREAD

**Issue by DonutMan06** [tareqdandachi/jekyll-shell-theme#1]
Hello,
An error is raised when I install this theme with the latest version of jekyll :

I added in my Gemfile
`gem "jekyll-shell-theme"` 

And in my config file 
`"theme: jekyll-shell-theme"`

But when I run bundle or bundle update:
```
$ bundle update
The dependency tzinfo (~> 1.2) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32 java`.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32 java`.
The dependency wdm (~> 0.1.1) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.2.0)

    jekyll-shell-theme was resolved to 0.1.0, which depends on
      jekyll (~> 3.8.5)
```

This issue is solved when I changed the requested jekyll version from 4.2.0 (i.e the latest one at the time of today) to 3.8.5

**Comment by itstorque** [comment]
I relaxed the runtime dependencies, this should be fixed now

**Comment by mateusdeap** [comment]
I know this issue is closed, but when installing this theme, I still get this error. I saw that the last commit changed the runtime dependency to read `>=`, so maybe it was not published to rubygems?...
